import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AppProviders } from "@/components/app-providers";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Modals } from "@/components/modals";
import { SubscriptionAlert } from "@/features/subscriptions/components/subsctiption-alert";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Canva Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${inter.className}`}>
          <AppProviders>
            <Toaster />
            <Modals />
            <SubscriptionAlert />
            {children}
          </AppProviders>
        </body>
      </html>
    </SessionProvider>
  );
}
